#!/usr/bin/env node
/**
 * chess-init — Scans repo and generates .chess/spec.yaml
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const REPO_ROOT = process.cwd();
const CHESS_DIR = path.join(REPO_ROOT, '.chess');
const SPEC_FILE = path.join(CHESS_DIR, 'spec.yaml');
const DEPS_FILE = path.join(CHESS_DIR, 'deps.json');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function detectLanguage() {
  const files = fs.readdirSync(REPO_ROOT);
  if (files.includes('package.json')) return 'javascript';
  if (files.includes('Cargo.toml')) return 'rust';
  if (files.includes('go.mod')) return 'go';
  if (files.includes('requirements.txt') || files.includes('pyproject.toml')) return 'python';
  if (files.includes('Gemfile')) return 'ruby';
  if (files.some(f => f.endsWith('.ts') || f.endsWith('.tsx'))) return 'typescript';
  if (files.some(f => f.endsWith('.js') || f.endsWith('.jsx'))) return 'javascript';
  return 'unknown';
}

function scanDependencies() {
  const deps = {};
  try {
    const pkgPath = path.join(REPO_ROOT, 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      deps.dependencies = Object.keys(pkg.dependencies || {});
      deps.devDependencies = Object.keys(pkg.devDependencies || {});
    }
  } catch (e) {}

  try {
    const reqPath = path.join(REPO_ROOT, 'requirements.txt');
    if (fs.existsSync(reqPath)) {
      deps.python = fs.readFileSync(reqPath, 'utf8')
        .split('\n')
        .map(l => l.trim().split('==')[0].split('>=')[0])
        .filter(Boolean);
    }
  } catch (e) {}

  return deps;
}

function findKeyFiles() {
  const keyFiles = [];
  const candidates = [
    'README.md', 'CLAUDE.md', 'ROADMAP.md', 'TODO.md',
    'CONTRIBUTING.md', 'ARCHITECTURE.md', 'API.md',
    'src/index.js', 'src/main.py', 'src/main.rs', 'src/main.go',
    'app.py', 'server.js', 'main.ts'
  ];
  for (const file of candidates) {
    if (fs.existsSync(path.join(REPO_ROOT, file))) {
      keyFiles.push(file);
    }
  }
  return keyFiles;
}

function buildSpec() {
  const lang = detectLanguage();
  const deps = scanDependencies();
  const keyFiles = findKeyFiles();

  const lines = [
    '# Chess Theory — Project Spec',
    '# Auto-generated by chess-init. Human-editable.',
    '',
    `language: ${lang}`,
    '',
    'key_files:',
    ...keyFiles.map(f => `  - ${f}`),
    '',
    'dependencies:',
    ...Object.entries(deps).flatMap(([k, v]) => [
      `  ${k}:`,
      ...v.slice(0, 10).map(d => `    - ${d}`),
      ...(v.length > 10 ? [`    # ... and ${v.length - 10} more`] : [])
    ]),
    '',
    'future:',
    '  # Add upcoming changes, migrations, deprecations here',
    '  # Example:',
    '  # auth.middleware.ts:',
    '  #   upcoming: {issue: 442, change: "oauth2-migration", eta: "14d"}',
    '  #   consumers: [user.ts, billing.ts, admin.ts]',
    '  #   constraint: "keep thin"',
    '  #   risk: "coupling here = rewrite cost"',
    '',
    'constraints:',
    '  # Add must/must-not rules here',
    '  # Example:',
    '  # - "Never modify auth.middleware.ts directly"',
    '  # - "All DB changes need migration files"',
    '',
    'roadmap:',
    '  # Add milestones here',
    '  # Example:',
    '  # - {milestone: "v2.0", eta: "2026-09-01", focus: "OAuth2 migration"}',
  ];

  return lines.join('\n');
}

function buildDepsGraph() {
  const graph = {};
  const keyFiles = findKeyFiles();

  for (const file of keyFiles) {
    const fullPath = path.join(REPO_ROOT, file);
    try {
      const content = fs.readFileSync(fullPath, 'utf8');
      const imports = [];

      const jsMatches = content.matchAll(/import\s+.*?\s+from\s+['"]([^'"]+)['"]/g);
      for (const m of jsMatches) imports.push(m[1]);

      const pyMatches = content.matchAll(/^(?:from|import)\s+(\S+)/gm);
      for (const m of pyMatches) imports.push(m[1]);

      graph[file] = { imports: imports.slice(0, 20) };
    } catch (e) {}
  }

  return graph;
}

function main() {
  console.log('🔧 chess-init — Scanning repo...\n');

  ensureDir(CHESS_DIR);

  const spec = buildSpec();
  fs.writeFileSync(SPEC_FILE, spec);
  console.log(`✅ Created: .chess/spec.yaml`);

  const deps = buildDepsGraph();
  fs.writeFileSync(DEPS_FILE, JSON.stringify(deps, null, 2));
  console.log(`✅ Created: .chess/deps.json`);

  const historyFile = path.join(CHESS_DIR, 'history.jsonl');
  if (!fs.existsSync(historyFile)) {
    fs.writeFileSync(historyFile, '');
    console.log(`✅ Created: .chess/history.jsonl`);
  }

  const patternsFile = path.join(CHESS_DIR, 'patterns.json');
  if (!fs.existsSync(patternsFile)) {
    fs.writeFileSync(patternsFile, '{}');
    console.log(`✅ Created: .chess/patterns.json`);
  }

  console.log('\n🎉 Repo initialized for Chess Theory!');
  console.log('\nNext: Type "/chess" in your agent to activate Three Selves.');
}

main();
